<?php
// Generated by tests/Loader/bin/extract-compiled-container.php from
// tangible-quiz-0.7.0.zip: var/container/CompiledContainer.php (sha256 a51c922c4bdbccaa3ce4107bd36fb3bb40c844f8891eb7edc92383e3680439fd).
// The factories below are verbatim but for the consumer namespace
// (Tangible\Quiz\ -> FxCompiled\Quiz\Consumer\). Do not edit by hand.

namespace FxCompiled\Quiz;

use Symfony\Component\DependencyInjection\Container;

class CompiledContainer extends Container
{
    public function __construct()
    {
        $this->parameters = [];
        $this->services = $this->privates = [];
        $this->methodMap = [
            'League\\Tactician\\CommandBus' => 'getCommandBusService',
            'TangibleDDD\\Application\\Correlation\\CorrelationMiddleware' => 'getCorrelationMiddlewareService',
            'TangibleDDD\\Application\\Events\\DomainEventsPublishMiddleware' => 'getDomainEventsPublishMiddlewareService',
            'TangibleDDD\\Application\\Events\\EventRouter' => 'getEventRouterService',
            'TangibleDDD\\Application\\Events\\EventsUnitOfWork' => 'getEventsUnitOfWorkService',
            'TangibleDDD\\Application\\Events\\IDomainEventDispatcher' => 'getIDomainEventDispatcherService',
            'TangibleDDD\\Application\\Events\\IIntegrationEventBus' => 'getIIntegrationEventBusService',
            'TangibleDDD\\Application\\Logging\\Redactor' => 'getRedactorService',
            'TangibleDDD\\Application\\Outbox\\IOutboxPublisher' => 'getIOutboxPublisherService',
            'TangibleDDD\\Application\\Outbox\\OutboxConfig' => 'getOutboxConfigService',
            'TangibleDDD\\Application\\Persistence\\TransactionMiddleware' => 'getTransactionMiddlewareService',
            'TangibleDDD\\Application\\Process\\ProcessRunner' => 'getProcessRunnerService',
            'TangibleDDD\\Infra\\IOutboxRepository' => 'getIOutboxRepositoryService',
            'TangibleDDD\\Infra\\IProcessRepository' => 'getIProcessRepositoryService',
            'TangibleDDD\\Infra\\Services\\OutboxProcessor' => 'getOutboxProcessorService',
            'tactician.query_bus' => 'getTactician_QueryBusService',
        ];
        $this->aliases = [
            'TangibleDDD\\Infra\\IDDDConfig' => 'FxCompiled\\Quiz\\Consumer\\Infra\\Config',
        ];
    }

    public function isCompiled(): bool
    {
        return true;
    }

    /**
     * @return \League\Tactician\CommandBus
     */
    protected static function getCommandBusService($container)
    {
        return $container->services['League\\Tactician\\CommandBus'] = new \League\Tactician\CommandBus(($container->services['TangibleDDD\\Application\\Correlation\\CorrelationMiddleware'] ?? self::getCorrelationMiddlewareService($container)), ($container->services['FxCompiled\\Quiz\\Consumer\\Application\\Middleware\\DoctrineTransactionMiddleware'] ??= new \FxCompiled\Quiz\Consumer\Application\Middleware\DoctrineTransactionMiddleware()), ($container->services['TangibleDDD\\Application\\Events\\DomainEventsPublishMiddleware'] ?? self::getDomainEventsPublishMiddlewareService($container)), new \League\Tactician\Handler\CommandHandlerMiddleware($container, new \League\Tactician\Handler\Mapping\MapByNamingConvention(($container->privates['tactician.class_name_inflector'] ??= new \TangibleDDD\Application\CQRS\HandlerClassNameInflector()), ($container->privates['tactician.method_name_inflector'] ??= new \League\Tactician\Handler\Mapping\MethodName\Handle()))));
    }

    /**
     * @return \TangibleDDD\Application\Correlation\CorrelationMiddleware
     */
    protected static function getCorrelationMiddlewareService($container)
    {
        return $container->services['TangibleDDD\\Application\\Correlation\\CorrelationMiddleware'] = new \TangibleDDD\Application\Correlation\CorrelationMiddleware(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')), ($container->services['TangibleDDD\\Application\\Events\\EventsUnitOfWork'] ??= new \TangibleDDD\Application\Events\EventsUnitOfWork()), ($container->services['TangibleDDD\\Application\\Logging\\Redactor'] ??= new \TangibleDDD\Application\Logging\Redactor()));
    }

    /**
     * @return \TangibleDDD\Application\Events\DomainEventsPublishMiddleware
     */
    protected static function getDomainEventsPublishMiddlewareService($container)
    {
        return $container->services['TangibleDDD\\Application\\Events\\DomainEventsPublishMiddleware'] = new \TangibleDDD\Application\Events\DomainEventsPublishMiddleware(($container->services['TangibleDDD\\Application\\Events\\EventsUnitOfWork'] ??= new \TangibleDDD\Application\Events\EventsUnitOfWork()), ($container->services['TangibleDDD\\Application\\Events\\EventRouter'] ?? self::getEventRouterService($container)));
    }

    /**
     * @return \TangibleDDD\Application\Events\EventRouter
     */
    protected static function getEventRouterService($container)
    {
        return $container->services['TangibleDDD\\Application\\Events\\EventRouter'] = new \TangibleDDD\Application\Events\EventRouter(($container->services['TangibleDDD\\Application\\Events\\IDomainEventDispatcher'] ??= new \TangibleDDD\Infra\Services\WordPressEventDispatcher()), ($container->services['TangibleDDD\\Application\\Events\\IIntegrationEventBus'] ?? self::getIIntegrationEventBusService($container)));
    }

    /**
     * @return \TangibleDDD\Application\Events\EventsUnitOfWork
     */
    protected static function getEventsUnitOfWorkService($container)
    {
        return $container->services['TangibleDDD\\Application\\Events\\EventsUnitOfWork'] = new \TangibleDDD\Application\Events\EventsUnitOfWork();
    }

    /**
     * @return \TangibleDDD\Infra\Services\WordPressEventDispatcher
     */
    protected static function getIDomainEventDispatcherService($container)
    {
        return $container->services['TangibleDDD\\Application\\Events\\IDomainEventDispatcher'] = new \TangibleDDD\Infra\Services\WordPressEventDispatcher();
    }

    /**
     * @return \TangibleDDD\Infra\Services\OutboxIntegrationEventBus
     */
    protected static function getIIntegrationEventBusService($container)
    {
        return $container->services['TangibleDDD\\Application\\Events\\IIntegrationEventBus'] = new \TangibleDDD\Infra\Services\OutboxIntegrationEventBus(($container->services['TangibleDDD\\Infra\\IOutboxRepository'] ?? self::getIOutboxRepositoryService($container)), ($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')));
    }

    /**
     * @return \TangibleDDD\Application\Logging\Redactor
     */
    protected static function getRedactorService($container)
    {
        return $container->services['TangibleDDD\\Application\\Logging\\Redactor'] = new \TangibleDDD\Application\Logging\Redactor();
    }

    /**
     * @return \TangibleDDD\Infra\Services\ActionSchedulerOutboxPublisher
     */
    protected static function getIOutboxPublisherService($container)
    {
        return $container->services['TangibleDDD\\Application\\Outbox\\IOutboxPublisher'] = new \TangibleDDD\Infra\Services\ActionSchedulerOutboxPublisher(($container->services['TangibleDDD\\Application\\Outbox\\OutboxConfig'] ?? self::getOutboxConfigService($container)));
    }

    /**
     * @return \TangibleDDD\Application\Outbox\OutboxConfig
     */
    protected static function getOutboxConfigService($container)
    {
        return $container->services['TangibleDDD\\Application\\Outbox\\OutboxConfig'] = \TangibleDDD\Application\Outbox\OutboxConfig::from_options(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')));
    }

    /**
     * @return \TangibleDDD\Application\Persistence\TransactionMiddleware
     */
    protected static function getTransactionMiddlewareService($container)
    {
        return $container->services['TangibleDDD\\Application\\Persistence\\TransactionMiddleware'] = new \TangibleDDD\Application\Persistence\TransactionMiddleware();
    }

    /**
     * @return \TangibleDDD\Application\Process\ProcessRunner
     */
    protected static function getProcessRunnerService($container)
    {
        return $container->services['TangibleDDD\\Application\\Process\\ProcessRunner'] = new \TangibleDDD\Application\Process\ProcessRunner(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')), ($container->services['TangibleDDD\\Infra\\IProcessRepository'] ?? self::getIProcessRepositoryService($container)));
    }

    /**
     * @return \TangibleDDD\Infra\Persistence\OutboxRepository
     */
    protected static function getIOutboxRepositoryService($container)
    {
        return $container->services['TangibleDDD\\Infra\\IOutboxRepository'] = new \TangibleDDD\Infra\Persistence\OutboxRepository(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')), ($container->services['TangibleDDD\\Application\\Outbox\\OutboxConfig'] ?? self::getOutboxConfigService($container)));
    }

    /**
     * @return \TangibleDDD\Infra\Persistence\ProcessRepository
     */
    protected static function getIProcessRepositoryService($container)
    {
        return $container->services['TangibleDDD\\Infra\\IProcessRepository'] = new \TangibleDDD\Infra\Persistence\ProcessRepository(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')));
    }

    /**
     * @return \TangibleDDD\Infra\Services\OutboxProcessor
     */
    protected static function getOutboxProcessorService($container)
    {
        return $container->services['TangibleDDD\\Infra\\Services\\OutboxProcessor'] = new \TangibleDDD\Infra\Services\OutboxProcessor(($container->services['FxCompiled\\Quiz\\Consumer\\Infra\\Config'] ??= new \FxCompiled\Quiz\Consumer\Infra\Config('dev')), ($container->services['TangibleDDD\\Infra\\IOutboxRepository'] ?? self::getIOutboxRepositoryService($container)), ($container->services['TangibleDDD\\Application\\Outbox\\OutboxConfig'] ?? self::getOutboxConfigService($container)), ($container->services['TangibleDDD\\Application\\Outbox\\IOutboxPublisher'] ?? self::getIOutboxPublisherService($container)));
    }

    /**
     * @return \League\Tactician\CommandBus
     */
    protected static function getTactician_QueryBusService($container)
    {
        return $container->services['tactician.query_bus'] = new \League\Tactician\CommandBus(new \League\Tactician\Handler\CommandHandlerMiddleware($container, new \League\Tactician\Handler\Mapping\MapByNamingConvention(($container->privates['tactician.class_name_inflector'] ??= new \TangibleDDD\Application\CQRS\HandlerClassNameInflector()), ($container->privates['tactician.method_name_inflector'] ??= new \League\Tactician\Handler\Mapping\MethodName\Handle()))));
    }
}
